    const mapData = [
  {
    "id": "west_central_10",
    "RegionName": "west central",
    "SiteName": "Family Health Center - Marshfield Dental Center",
    "SiteAddress": "1307 N Saint Joseph Ave",
    "SiteCity": "Marshfield",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -90.17993972,
    "YCoordinate": 44.68088751,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 9
  },
  {
    "id": "west_central_11",
    "RegionName": "west central",
    "SiteName": "Family Health Center - Chippewa Falls Dental Center",
    "SiteAddress": "850 Lakeland Dr",
    "SiteCity": "Chippewa Falls",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -91.3546114,
    "YCoordinate": 44.95083056,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 9
  },
  {
    "id": "west_central_12",
    "RegionName": "west central",
    "SiteName": "Family Health Center - Menomonie Dental Center",
    "SiteAddress": "404 Red Cedar St",
    "SiteCity": "Menomonie",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -91.89652122,
    "YCoordinate": 44.88119257,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 9
  },
  {
    "id": "west_central_13",
    "RegionName": "west central",
    "SiteName": "Family Health Center - Neillsville Dental Center",
    "SiteAddress": "8 Boon Blvd",
    "SiteCity": "Neillsville",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -90.58643771,
    "YCoordinate": 44.55022847,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 9
  },
  {
    "id": "west_central_15",
    "RegionName": "west central",
    "SiteName": "Family Health Center - Black River Falls Dental Center",
    "SiteAddress": "N6571 Lumberjack Guy Rd",
    "SiteCity": "Black River Falls",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -90.804938,
    "YCoordinate": 44.30823824,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 9
  },
  {
    "id": "west_central_17",
    "RegionName": "west central",
    "SiteName": "Family Health Center - Rice Lake Dental Center",
    "SiteAddress": "1501 W Stout St",
    "SiteCity": "Rice Lake",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -91.7590461,
    "YCoordinate": 45.50794767,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 9
  },
  {
    "id": "west_central_18",
    "RegionName": "west central",
    "SiteName": "Family Health Center - Medford Dental Center",
    "SiteAddress": "843 W Broadway Ave",
    "SiteCity": "Medford",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -90.36127758,
    "YCoordinate": 45.14045863,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 9
  },
  {
    "id": "west_central_20",
    "RegionName": "west central",
    "SiteName": "Family Health Center - Marshfield Primary Care Center",
    "SiteAddress": "630 S Central Ave STE 600B",
    "SiteCity": "Marshfield",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -90.17728299,
    "YCoordinate": 44.66167438,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 9
  },
  {
    "id": "west_central_21",
    "RegionName": "west central",
    "SiteName": "Family Health Center - Marshfield Alcohol and Drug Recovery Center",
    "SiteAddress": "630 S Central Ave",
    "SiteCity": "Marshfield",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -90.17736563,
    "YCoordinate": 44.66167166,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 9
  },
  {
    "id": "west_central_44",
    "RegionName": "west central",
    "SiteName": "Northlakes Community Clinic - Cumberland",
    "SiteAddress": "1150 6th Ave",
    "SiteCity": "Cumberland",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -92.02818968,
    "YCoordinate": 45.53157432,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 9
  },
  {
    "id": "west_central_46",
    "RegionName": "west central",
    "SiteName": "Northlakes Community Clinic - Augusta",
    "SiteAddress": "207 W Lincoln St",
    "SiteCity": "Augusta",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -91.1224305,
    "YCoordinate": 44.68003767,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 9
  },
  {
    "id": "west_central_47",
    "RegionName": "west central",
    "SiteName": "Northlakes Community Clinic - Eau Claire - Oak Ridge",
    "SiteAddress": "2119 Heights Dr",
    "SiteCity": "Eau Claire",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -91.51510062,
    "YCoordinate": 44.79644801,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 9
  },
  {
    "id": "west_central_51",
    "RegionName": "west central",
    "SiteName": "NorthLakes Community Clinic--Turtle Lake",
    "SiteAddress": "730 Swede",
    "SiteCity": "Turtle Lake",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -92.16281118,
    "YCoordinate": 45.38761099,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 9
  },
  {
    "id": "west_central_52",
    "RegionName": "west central",
    "SiteName": "NorthLakes Community Clinic Eau Claire - Clairemont Avenue",
    "SiteAddress": "1002 W Clairemont Ave",
    "SiteCity": "Eau Claire",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -91.51606169,
    "YCoordinate": 44.79334931,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 9
  },
  {
    "id": "west_central_54",
    "RegionName": "west central",
    "SiteName": "NorthLakes Community Clinic - Rice Lake New",
    "SiteAddress": "1051 West Ave",
    "SiteCity": "Rice Lake",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -91.76493925,
    "YCoordinate": 45.51268294,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 9
  },
  {
    "id": "southern_1",
    "RegionName": "Southern",
    "SiteName": "Access Community Health Centers - Dodgeville Dental Clinic",
    "SiteAddress": "103 E Fountain St",
    "SiteCity": "Dodgeville",
    "HealthCenterName": "Access Community Health Centers",
    "XCoordinate": -90.12967068,
    "YCoordinate": 42.95896703,
    "website": "https://www.wphca.org/access-workforce",
    "Region": 7
  },
  {
    "id": "southern_2",
    "RegionName": "Southern",
    "SiteName": "Access Community Health Centers - Sun Prairie Dental Clinic",
    "SiteAddress": "1270 W Main St",
    "SiteCity": "Sun Prairie",
    "HealthCenterName": "Access Community Health Centers",
    "XCoordinate": -89.23493629,
    "YCoordinate": 43.17955567,
    "website": "https://www.wphca.org/access-workforce",
    "Region": 7
  },
  {
    "id": "southern_3",
    "RegionName": "Southern",
    "SiteName": "Access Community Health Centers - Wingra Family Medical Center",
    "SiteAddress": "1102 S Park St",
    "SiteCity": "Madison",
    "HealthCenterName": "Access Community Health Centers",
    "XCoordinate": -89.39768729,
    "YCoordinate": 43.0553331,
    "website": "https://www.wphca.org/access-workforce",
    "Region": 7
  },
  {
    "id": "southern_4",
    "RegionName": "Southern",
    "SiteName": "Access Community Health Centers - William T. Evjue Clinic",
    "SiteAddress": "3434 E Washington Ave",
    "SiteCity": "Madison",
    "HealthCenterName": "Access Community Health Centers",
    "XCoordinate": -89.3294311,
    "YCoordinate": 43.11393669,
    "website": "https://www.wphca.org/access-workforce",
    "Region": 7
  },
  {
    "id": "southern_5",
    "RegionName": "Southern",
    "SiteName": "Access Community Health Centers - Joyce & Marshall Erdman Clinic",
    "SiteAddress": "2202 S Park St",
    "SiteCity": "Madison",
    "HealthCenterName": "Access Community Health Centers",
    "XCoordinate": -89.3941264,
    "YCoordinate": 43.04221517,
    "website": "https://www.wphca.org/access-workforce",
    "Region": 7
  },
  {
    "id": "southern_9",
    "RegionName": "Southern",
    "SiteName": "Beloit Area Community Health Center",
    "SiteAddress": "55 Eclipse Ctr",
    "SiteCity": "Beloit",
    "HealthCenterName": "Community Health Systems",
    "XCoordinate": -89.03222843,
    "YCoordinate": 42.51928914,
    "website": "https://www.wphca.org/chs-workforce",
    "Region": 7
  },
  {
    "id": "southern_79",
    "RegionName": "Southern",
    "SiteName": "Rock River Community Clinic - Watertown",
    "SiteAddress": "132 Hospital Dr",
    "SiteCity": "Watertown",
    "HealthCenterName": "Rock River Community Clinic",
    "XCoordinate": -88.69903713,
    "YCoordinate": 43.20087571,
    "website": "https://www.wphca.org/rock-river-workforce",
    "Region": 7
  },
  {
    "id": "southern_80",
    "RegionName": "Southern",
    "SiteName": "Rock River Community Clinic - Whitewater",
    "SiteAddress": "1461 W Main St BLDG",
    "SiteCity": "Whitewater",
    "HealthCenterName": "Rock River Community Clinic",
    "XCoordinate": -88.76337704,
    "YCoordinate": 42.83557657,
    "website": "https://www.wphca.org/rock-river-workforce",
    "Region": 7
  },
  {
    "id": "southern_81",
    "RegionName": "Southern",
    "SiteName": "Rock River Community Clinic - Fort Atkinson",
    "SiteAddress": "520 Handeyside Ln",
    "SiteCity": "Fort Atkinson",
    "HealthCenterName": "Rock River Community Clinic",
    "XCoordinate": -88.82912762,
    "YCoordinate": 42.9351504,
    "website": "https://www.wphca.org/rock-river-workforce",
    "Region": 7
  },
  {
    "id": "northeast_6",
    "RegionName": "Northeast",
    "SiteName": "Bridge Community Health Clinic - Antigo Dental",
    "SiteAddress": "1111 Langlade Rd",
    "SiteCity": "Antigo",
    "HealthCenterName": "Bridge Community Health Clinic",
    "XCoordinate": -89.13519508,
    "YCoordinate": 45.14724508,
    "website": "https://www.wphca.org/bridge-workforce",
    "Region": 2
  },
  {
    "id": "northeast_7",
    "RegionName": "Northeast",
    "SiteName": "Bridge Community Health Clinic - Behavioral Health East",
    "SiteAddress": "731 N 1st St STE 5000",
    "SiteCity": "Wausau",
    "HealthCenterName": "Bridge Community Health Clinic",
    "XCoordinate": -89.62985948,
    "YCoordinate": 44.96274719,
    "website": "https://www.wphca.org/bridge-workforce",
    "Region": 2
  },
  {
    "id": "northeast_8",
    "RegionName": "Northeast",
    "SiteName": "Bridge Community Health Clinic - Wausau",
    "SiteAddress": "1810 N 2nd St",
    "SiteCity": "Wausau",
    "HealthCenterName": "Bridge Community Health Clinic",
    "XCoordinate": -89.62845558,
    "YCoordinate": 44.9716292,
    "website": "https://www.wphca.org/bridge-workforce",
    "Region": 2
  },
  {
    "id": "northeast_14",
    "RegionName": "Northeast",
    "SiteName": "Family Health Center - Rhinelander Dental Center",
    "SiteAddress": "2268 N Shore Dr",
    "SiteCity": "Rhinelander",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -89.37277267,
    "YCoordinate": 45.6371063,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 2
  },
  {
    "id": "northeast_16",
    "RegionName": "Northeast",
    "SiteName": "Family Health Center - Park Falls Dental Center",
    "SiteAddress": "75 Sherry Ave",
    "SiteCity": "Park Falls",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -90.44199824,
    "YCoordinate": 45.93088249,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 2
  },
  {
    "id": "northeast_23",
    "RegionName": "Northeast",
    "SiteName": "Family Health Center - Minocqua Alcohol and Drug Recovery Center",
    "SiteAddress": "9792 Sth 70",
    "SiteCity": "Minocqua",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -89.72208505,
    "YCoordinate": 45.88619362,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 2
  },
  {
    "id": "northeast_45",
    "RegionName": "Northeast",
    "SiteName": "Northlakes Community Clinic - Marinette",
    "SiteAddress": "1435 Cleveland Ave",
    "SiteCity": "Marinette",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -87.6255989,
    "YCoordinate": 45.08532842,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 2
  },
  {
    "id": "northeast_48",
    "RegionName": "Northeast",
    "SiteName": "Northlakes Community Clinic - White Lake",
    "SiteAddress": "524 Bissell St",
    "SiteCity": "White Lake",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -88.76449318,
    "YCoordinate": 45.15709696,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 2
  },
  {
    "id": "northeast_53",
    "RegionName": "Northeast",
    "SiteName": "NorthLakes Community Clinic - Oconto",
    "SiteAddress": "155 Memorial Dr",
    "SiteCity": "Oconto",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -87.8683622,
    "YCoordinate": 44.89729838,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 2
  },
  {
    "id": "northeast_57",
    "RegionName": "Northeast",
    "SiteName": "NorthLakes Community Clinic - Hurley",
    "SiteAddress": "115 5th Ave N",
    "SiteCity": "Hurley",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -90.18616085,
    "YCoordinate": 46.45074941,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 2
  },
  {
    "id": "northeast_58",
    "RegionName": "Northeast",
    "SiteName": "NorthLakes Community Clinic- Park Falls",
    "SiteAddress": "110 2nd Ave N",
    "SiteCity": "Park Falls",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -90.44906368,
    "YCoordinate": 45.93535092,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 2
  },
  {
    "id": "northeast_60",
    "RegionName": "Northeast",
    "SiteName": "NorthLakes Community Clinic - Lakewood",
    "SiteAddress": "15397 State Highway 32",
    "SiteCity": "Lakewood",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -88.52703839,
    "YCoordinate": 45.30131129,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 2
  },
  {
    "id": "northern_19",
    "RegionName": "Northern",
    "SiteName": "Family Health Center - Ladysmith Dental Center",
    "SiteAddress": "315 Miner Ave W",
    "SiteCity": "Ladysmith",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -91.10435048,
    "YCoordinate": 45.46423516,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 1
  },
  {
    "id": "northern_22",
    "RegionName": "Northern",
    "SiteName": "Family Health Center - Ladysmith Alcohol and Drug Recovery Center",
    "SiteAddress": "200 W 5th St S",
    "SiteCity": "Ladysmith",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -91.1062237,
    "YCoordinate": 45.46331869,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 1
  },
  {
    "id": "northern_25",
    "RegionName": "Northern",
    "SiteName": "Lake Superior Community Health Center - Superior Clinic",
    "SiteAddress": "2222 E 5th St",
    "SiteCity": "Superior",
    "HealthCenterName": "Lake Superior Community Health Center",
    "XCoordinate": -92.04969295,
    "YCoordinate": 46.70425794,
    "website": "https://www.wphca.org/lakesuperior-workforce",
    "Region": 1
  },
  {
    "id": "northern_42",
    "RegionName": "Northern",
    "SiteName": "Northlakes Community Clinic - Solon Springs",
    "SiteAddress": "11178 O&#39;Brien Parkway",
    "SiteCity": "Solon Springs",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -91.6777397,
    "YCoordinate": 46.33094109,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 1
  },
  {
    "id": "northern_43",
    "RegionName": "Northern",
    "SiteName": "Northlakes Northlakes Community Clinic - Washburn",
    "SiteAddress": "320 Superior Ave",
    "SiteCity": "Washburn",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -90.88251973,
    "YCoordinate": 46.68070873,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 1
  },
  {
    "id": "northern_49",
    "RegionName": "Northern",
    "SiteName": "Northlakes Community Clinic - Minong",
    "SiteAddress": "600 W Shell Creek Rd",
    "SiteCity": "Minong",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -91.82988542,
    "YCoordinate": 46.10385383,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 1
  },
  {
    "id": "northern_50",
    "RegionName": "Northern",
    "SiteName": "Northlakes Community Clinic - Iron River",
    "SiteAddress": "7665 US Highway 2",
    "SiteCity": "Iron River",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -91.41508062,
    "YCoordinate": 46.56502397,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 1
  },
  {
    "id": "northern_55",
    "RegionName": "Northern",
    "SiteName": "NorthLakes Community Clinic - Ashland Downtown",
    "SiteAddress": "300 Main St W",
    "SiteCity": "Ashland",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -90.88602856,
    "YCoordinate": 46.59024935,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 1
  },
  {
    "id": "northern_56",
    "RegionName": "Northern",
    "SiteName": "NorthLakes Community Clinic - Poplar",
    "SiteAddress": "9675 E Elm Rd",
    "SiteCity": "Poplar",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -91.80088244,
    "YCoordinate": 46.58291769,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 1
  },
  {
    "id": "northern_59",
    "RegionName": "Northern",
    "SiteName": "NorthLakes Community Clinic - River'S Edge",
    "SiteAddress": "15954 Rivers Edge Dr",
    "SiteCity": "Hayward",
    "HealthCenterName": "NorthLakes Community Clinics",
    "XCoordinate": -91.48659712,
    "YCoordinate": 46.00491749,
    "website": "https://www.wphca.org/northlakes-workforce",
    "Region": 1
  },
  {
    "id": "eastern_26",
    "RegionName": "Eastern",
    "SiteName": "Lakeshore Community Health Care - West Bend",
    "SiteAddress": "908 W Washington St",
    "SiteCity": "West Bend",
    "HealthCenterName": "Lakeshore Community Health Care",
    "XCoordinate": -88.18782947,
    "YCoordinate": 43.42687177,
    "website": "https://www.wphca.org/lakeshore-workforce",
    "Region": 3
  },
  {
    "id": "eastern_27",
    "RegionName": "Eastern",
    "SiteName": "Lakeshore Community Health Care - Sheboygan",
    "SiteAddress": "1721 Saemann Ave",
    "SiteCity": "Sheboygan",
    "HealthCenterName": "Lakeshore Community Health Care",
    "XCoordinate": -87.72895028,
    "YCoordinate": 43.76427569,
    "website": "https://www.wphca.org/lakeshore-workforce",
    "Region": 3
  },
  {
    "id": "eastern_28",
    "RegionName": "Eastern",
    "SiteName": "Lakeshore Community Health Care - Calumet",
    "SiteAddress": "2719 Calumet Ave STE A",
    "SiteCity": "Manitowoc",
    "HealthCenterName": "Lakeshore Community Health Care",
    "XCoordinate": -87.68308668,
    "YCoordinate": 44.08668941,
    "website": "https://www.wphca.org/lakeshore-workforce",
    "Region": 3
  },
  {
    "id": "eastern_32",
    "RegionName": "Eastern",
    "SiteName": "N.E.W. Community Clinc - Door County Dental",
    "SiteAddress": "228 S 18th Ave",
    "SiteCity": "Sturgeon Bay",
    "HealthCenterName": "N.E.W. Community Clinic",
    "XCoordinate": -87.35139893,
    "YCoordinate": 44.83347197,
    "website": "https://www.wphca.org/new-workforce",
    "Region": 3
  },
  {
    "id": "eastern_33",
    "RegionName": "Eastern",
    "SiteName": "N.E.W. Community Clinic - Dental, Behavioral Health, and WIC - South Monroe",
    "SiteAddress": "424 S Monroe Ave, Ste 106",
    "SiteCity": "Green Bay",
    "HealthCenterName": "N.E.W. Community Clinic",
    "XCoordinate": -88.01365478,
    "YCoordinate": 44.50790305,
    "website": "https://www.wphca.org/new-workforce",
    "Region": 3
  },
  {
    "id": "eastern_34",
    "RegionName": "Eastern",
    "SiteName": "N.E.W. Community Clinic - Clinic at NorthWest Technical College",
    "SiteAddress": "2740 W Mason St",
    "SiteCity": "Green Bay",
    "HealthCenterName": "N.E.W. Community Clinic",
    "XCoordinate": -88.10388303,
    "YCoordinate": 44.52908898,
    "website": "https://www.wphca.org/new-workforce",
    "Region": 3
  },
  {
    "id": "eastern_35",
    "RegionName": "Eastern",
    "SiteName": "N.E.W. Community Clinic",
    "SiteAddress": "610 N Broadway",
    "SiteCity": "Green Bay",
    "HealthCenterName": "N.E.W. Community Clinic",
    "XCoordinate": -88.01660697,
    "YCoordinate": 44.52391697,
    "website": "https://www.wphca.org/new-workforce",
    "Region": 3
  },
  {
    "id": "east_central_67",
    "RegionName": "East Central",
    "SiteName": "Partnership Community Health Center - Waupaca Dental",
    "SiteAddress": "825 W Fulton St",
    "SiteCity": "Waupaca",
    "HealthCenterName": "Partnership Community Health Center",
    "XCoordinate": -89.10227507,
    "YCoordinate": 44.35730787,
    "website": "https://www.wphca.org/partnership-workforce",
    "Region": 4
  },
  {
    "id": "east_central_68",
    "RegionName": "East Central",
    "SiteName": "Partnership Dental City Center - Oshkosh",
    "SiteAddress": "550 City Ctr",
    "SiteCity": "Oshkosh",
    "HealthCenterName": "Partnership Community Health Center",
    "XCoordinate": -88.54030157,
    "YCoordinate": 44.01623616,
    "website": "https://www.wphca.org/partnership-workforce",
    "Region": 4
  },
  {
    "id": "east_central_69",
    "RegionName": "East Central",
    "SiteName": "Partnership Community Health Center - Appleton Dental",
    "SiteAddress": "5337 W Grande Market Dr",
    "SiteCity": "Appleton",
    "HealthCenterName": "Partnership Community Health Center",
    "XCoordinate": -88.48786514,
    "YCoordinate": 44.26388686,
    "website": "https://www.wphca.org/partnership-workforce",
    "Region": 4
  },
  {
    "id": "east_central_70",
    "RegionName": "East Central",
    "SiteName": "Partnership Community Health Center",
    "SiteAddress": "5471 W Waterford Ln",
    "SiteCity": "Appleton",
    "HealthCenterName": "Partnership Community Health Center",
    "XCoordinate": -88.48902897,
    "YCoordinate": 44.26316719,
    "website": "https://www.wphca.org/partnership-workforce",
    "Region": 4
  },
  {
    "id": "central_36",
    "RegionName": "Central",
    "SiteName": "Noble Community Clinics - Beaver Dam Spring Street",
    "SiteAddress": "1701 N Spring St",
    "SiteCity": "Beaver Dam",
    "HealthCenterName": "Noble Community Clinics",
    "XCoordinate": -88.82193662,
    "YCoordinate": 43.47844478,
    "website": "https://www.wphca.org/noble-workforce",
    "Region": 5
  },
  {
    "id": "central_37",
    "RegionName": "Central",
    "SiteName": "Noble Community Clinics - Friendship",
    "SiteAddress": "302 W Lake St",
    "SiteCity": "Friendship",
    "HealthCenterName": "Noble Community Clinics",
    "XCoordinate": -89.81998006,
    "YCoordinate": 43.97396618,
    "website": "https://www.wphca.org/noble-workforce",
    "Region": 5
  },
  
  {
    "id": "central_85",
    "RegionName": "Central",
    "SiteName": "Scenic Bluffs Health Center- Reedsburg",
    "SiteAddress": "1900 N Dewey Ave",
    "SiteCity": "Reedsburg",
    "HealthCenterName": "Scenic Bluffs Health Center",
     "XCoordinate": -89.99452582,
    "YCoordinate": "43.54891601",
    "website": "https://www.wphca.org/scenic-bluffs-workforce",
    "Region": "5"
  },
  {
    "id": "central_79",
    "RegionName": "Central",
    "SiteName": "Rock River Community Clinic - Watertown",
    "SiteAddress": "132 Hospital Dr",
    "SiteCity": "Watertown",
    "HealthCenterName": "Rock River Community Clinic",
     "XCoordinate":-88.69903713,
    "YCoordinate": "43.20087571",
    "website": "https://www.wphca.org/rock-river-workforce",
    "Region": "5"
  },
  {
    "id": "central_38",
    "RegionName": "Central",
    "SiteName": "Noble Community Clinics - Beaver Dam",
    "SiteAddress": "207 S University Ave",
    "SiteCity": "Beaver Dam",
    "HealthCenterName": "Noble Community Clinics",
    "XCoordinate": -88.82884364,
    "YCoordinate": 43.45505743,
    "website": "https://www.wphca.org/noble-workforce",
    "Region": 5
  },
  {
    "id": "central_39",
    "RegionName": "Central",
    "SiteName": "Noble Community Clinics - Mauston",
    "SiteAddress": "880 Herriot Dr",
    "SiteCity": "Mauston",
    "HealthCenterName": "Noble Community Clinics",
    "XCoordinate": -90.05900612,
    "YCoordinate": 43.80114118,
    "website": "https://www.wphca.org/noble-workforce",
    "Region": 5
  },
  {
    "id": "central_40",
    "RegionName": "Central",
    "SiteName": "Noble Community Clinics - Stevens Point Clinic",
    "SiteAddress": "2501 Main St",
    "SiteCity": "Stevens Point",
    "HealthCenterName": "Noble Community Clinics",
    "XCoordinate": -89.56228138,
    "YCoordinate": 44.52352386,
    "website": "https://www.wphca.org/noble-workforce",
    "Region": 5
  },
  {
    "id": "central_41",
    "RegionName": "Central",
    "SiteName": "Noble Community Clinics - Wautoma",
    "SiteAddress": "400 S Townline Rd",
    "SiteCity": "Wautoma",
    "HealthCenterName": "Noble Community Clinics",
    "XCoordinate": -89.27738468,
    "YCoordinate": 44.06705274,
    "website": "https://www.wphca.org/noble-workforce",
    "Region": 5
  },
  {
    "id": "western_82",
    "RegionName": "Western",
    "SiteName": "Scenic Bluffs Community Health Center - Norwalk",
    "SiteAddress": "200 W North St",
    "SiteCity": "Norwalk",
    "HealthCenterName": "Scenic Bluffs Health Center",
    "XCoordinate": -90.62430087,
    "YCoordinate": 43.83389079,
    "website": "https://www.wphca.org/scenic-bluffs-workforce",
    "Region": 8
  },
  {
    "id": "western_83",
    "RegionName": "Western",
    "SiteName": "Scenic Bluffs Health Center Inc - Lacrosse",
    "SiteAddress": "2030 7th St S",
    "SiteCity": "La Crosse",
    "HealthCenterName": "Scenic Bluffs Health Center",
    "XCoordinate": -91.24956913,
    "YCoordinate": 43.79118147,
    "website": "https://www.wphca.org/scenic-bluffs-workforce",
    "Region": 8
  },
  {
    "id": "western_84",
    "RegionName": "Western",
    "SiteName": "Scenic Bluffs Health Centers Inc- Reach Lacrosse",
    "SiteAddress": "212 11th St S",
    "SiteCity": "La Crosse",
    "HealthCenterName": "Scenic Bluffs Health Center",
    "XCoordinate": -91.24105848,
    "YCoordinate": 43.80944606,
    "website": "https://www.wphca.org/scenic-bluffs-workforce",
    "Region": 8
  },
  {
    "id": "western_86",
    "RegionName": "Western",
    "SiteName": "Scenic Bluffs Chc - Cashton",
    "SiteAddress": "238 Front St",
    "SiteCity": "Cashton",
    "HealthCenterName": "Scenic Bluffs Health Center",
    "XCoordinate": -90.7868061,
    "YCoordinate": 43.74037737,
    "website": "https://www.wphca.org/scenic-bluffs-workforce",
    "Region": 8
  },
  {
    "id": "southeast_24",
    "RegionName": "Southeast",
    "SiteName": "Gerald L. Ignace Indian Health Center, Inc.",
    "SiteAddress": "930 W Historic Mitchell St",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Family Health Center",
    "XCoordinate": -87.92368569,
    "YCoordinate": 43.01232501,
    "website": "https://www.wphca.org/fhc-workforce",
    "Region": 6
  },
  {
    "id": "southeast_29",
    "RegionName": "Southeast",
    "SiteName": "MHSI - Isaac Coggs Heritage Health Center",
    "SiteAddress": "8200 W Silver Spring Dr",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Milwaukee Health Services, Inc.",
    "XCoordinate": -88.01399701,
    "YCoordinate": 43.11967339,
    "website": "https://www.wphca.org/mhsi-workforce",
    "Region": 6
  },
  {
    "id": "southeast_30",
    "RegionName": "Southeast",
    "SiteName": "Milwaukee Health Services, Inc.",
    "SiteAddress": "2555 N Dr Martin Luther King Jr Dr",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Milwaukee Health Services, Inc.",
    "XCoordinate": -87.91440802,
    "YCoordinate": 43.065462,
    "website": "https://www.wphca.org/mhsi-workforce",
    "Region": 6
  },
  {
    "id": "southeast_31",
    "RegionName": "Southeast",
    "SiteName": "Muslim Community & Health Center",
    "SiteAddress": "803 W Layton Ave",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Muslim Community and Health Center",
    "XCoordinate": -87.92232405,
    "YCoordinate": 42.95913437,
    "website": "https://www.wphca.org/mchc-workforce",
    "Region": 6
  },
  {
    "id": "southeast_61",
    "RegionName": "Southeast",
    "SiteName": "Outreach Community Health Centers - Ascension St. Ben's Clinic",
    "SiteAddress": "1004 N 10th St, Ste 100",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Outreach Community Health Centers",
    "XCoordinate": -87.92434795,
    "YCoordinate": 43.04378724,
    "website": "https://www.wphca.org/outreach-workforce",
    "Region": 6
  },
  {
    "id": "southeast_62",
    "RegionName": "Southeast",
    "SiteName": "Outreach Community Health Centers - C. H. Mason Health Clinic",
    "SiteAddress": "4858 N Mother Daniels Way",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Outreach Community Health Centers",
    "XCoordinate": -87.95649456,
    "YCoordinate": 43.1060691,
    "website": "https://www.wphca.org/outreach-workforce",
    "Region": 6
  },
  {
    "id": "southeast_63",
    "RegionName": "Southeast",
    "SiteName": "Outreach Community Health Centers",
    "SiteAddress": "220 W Capitol Dr",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Outreach Community Health Centers",
    "XCoordinate": -87.91056064,
    "YCoordinate": 43.08934225,
    "website": "https://www.wphca.org/outreach-workforce",
    "Region": 6
  },
  {
    "id": "southeast_64",
    "RegionName": "Southeast",
    "SiteName": "Outreach Community Health Centers, Incorporated",
    "SiteAddress": "711 W Capitol Dr",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Outreach Community Health Centers",
    "XCoordinate": -87.92007636,
    "YCoordinate": 43.08926191,
    "website": "https://www.wphca.org/outreach-workforce",
    "Region": 6
  },
  {
    "id": "southeast_65",
    "RegionName": "Southeast",
    "SiteName": "Outreach Community Health Centers - Salvation Army Clinic",
    "SiteAddress": "1730 N 7th St",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Outreach Community Health Centers",
    "XCoordinate": -87.92005733,
    "YCoordinate": 43.05376229,
    "website": "https://www.wphca.org/outreach-workforce",
    "Region": 6
  },
  {
    "id": "southeast_66",
    "RegionName": "Southeast",
    "SiteName": "Outreach Community Health Centers - Racine",
    "SiteAddress": "3805 Spring St",
    "SiteCity": "Racine",
    "HealthCenterName": "Outreach Community Health Centers",
    "XCoordinate": -87.79538478,
    "YCoordinate": 42.73276686,
    "website": "https://www.wphca.org/outreach-workforce",
    "Region": 6
  },
  {
    "id": "southeast_71",
    "RegionName": "Southeast",
    "SiteName": "Pillar Health - Silver Lake",
    "SiteAddress": "903 S 2nd St",
    "SiteCity": "Silver Lake",
    "HealthCenterName": "Pillar Health",
    "XCoordinate": -88.16958114,
    "YCoordinate": 42.54229282,
    "website": "https://www.wphca.org/pillar-workforce",
    "Region": 6
  },
  {
    "id": "southeast_72",
    "RegionName": "Southeast",
    "SiteName": "Pillar Health - Kenosha",
    "SiteAddress": "4006 Washington Rd",
    "SiteCity": "Kenosha",
    "HealthCenterName": "Pillar Health",
    "XCoordinate": -87.85745147,
    "YCoordinate": 42.60307632,
    "website": "https://www.wphca.org/pillar-workforce",
    "Region": 6
  },
  {
    "id": "southeast_73",
    "RegionName": "Southeast",
    "SiteName": "Pillar Health - 22nd Ave",
    "SiteAddress": "4536 22nd Ave",
    "SiteCity": "Kenosha",
    "HealthCenterName": "Pillar Health",
    "XCoordinate": -87.83570044,
    "YCoordinate": 42.59419046,
    "website": "https://www.wphca.org/pillar-workforce",
    "Region": 6
  },
  {
    "id": "southeast_74",
    "RegionName": "Southeast",
    "SiteName": "Pillar Health - 14th Ave",
    "SiteAddress": "6226 14th Ave",
    "SiteCity": "Kenosha",
    "HealthCenterName": "Pillar Health",
    "XCoordinate": -87.82713522,
    "YCoordinate": 42.57809834,
    "website": "https://www.wphca.org/pillar-workforce",
    "Region": 6
  },
  {
    "id": "southeast_75",
    "RegionName": "Southeast",
    "SiteName": "Pillar Health - Racine",
    "SiteAddress": "930 Dr. Martin Luther King Dr",
    "SiteCity": "Racine",
    "HealthCenterName": "Pillar Health",
    "XCoordinate": -87.82881712,
    "YCoordinate": 42.73128037,
    "website": "https://www.wphca.org/pillar-workforce",
    "Region": 6
  },
  {
    "id": "southeast_76",
    "RegionName": "Southeast",
    "SiteName": "Progressive Community Health Center - Hillside Family Health Center",
    "SiteAddress": "1452 N 7th St",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Progressive Community Health Centers",
    "XCoordinate": -87.92008424,
    "YCoordinate": 43.04970226,
    "website": "https://www.wphca.org/progressive-workforce",
    "Region": 6
  },
  {
    "id": "southeast_77",
    "RegionName": "Southeast",
    "SiteName": "Progressive Community Health Center - Lisbon Avenue Health Center",
    "SiteAddress": "3522 W Lisbon Ave",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Progressive Community Health Centers",
    "XCoordinate": -87.95821561,
    "YCoordinate": 43.054748,
    "website": "https://www.wphca.org/progressive-workforce",
    "Region": 6
  },
  {
    "id": "southeast_78",
    "RegionName": "Southeast",
    "SiteName": "Progressive Community Health Center -12th Street Urgent Care",
    "SiteAddress": "945 N 12th St",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Progressive Community Health Centers",
    "XCoordinate": -87.92721188,
    "YCoordinate": 43.04256109,
    "website": "https://www.wphca.org/progressive-workforce",
    "Region": 6
  },
  {
    "id": "southeast_87",
    "RegionName": "Southeast",
    "SiteName": "Sixteenth Street Community Health Centers - UCC Senior Center",
    "SiteAddress": "730 W Washington St",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Sixteenth Street Community Health Center",
    "XCoordinate": -87.92052949,
    "YCoordinate": 43.02016343,
    "website": "https://www.wphca.org/sixteenth-st-workforce",
    "Region": 6
  },
  {
    "id": "southeast_88",
    "RegionName": "Southeast",
    "SiteName": "Sixteenth Street Community Health Centers - Mental Health Support Center",
    "SiteAddress": "1635 W National Ave",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Sixteenth Street Community Health Center",
    "XCoordinate": -87.93390935,
    "YCoordinate": 43.02289933,
    "website": "https://www.wphca.org/sixteenth-st-workforce",
    "Region": 6
  },
  {
    "id": "southeast_89",
    "RegionName": "Southeast",
    "SiteName": "Sixteenth Street Community Health Centers - Waukesha",
    "SiteAddress": "309 E North St",
    "SiteCity": "Waukesha",
    "HealthCenterName": "Sixteenth Street Community Health Center",
    "XCoordinate": -88.23373891,
    "YCoordinate": 43.01494368,
    "website": "https://www.wphca.org/sixteenth-st-workforce",
    "Region": 6
  },
  {
    "id": "southeast_90",
    "RegionName": "Southeast",
    "SiteName": "Sixteenth Street Community Health Centers - Layton",
    "SiteAddress": "4570 S 27th St",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Sixteenth Street Community Health Center",
    "XCoordinate": -87.9484994,
    "YCoordinate": 42.96187622,
    "website": "https://www.wphca.org/sixteenth-st-workforce",
    "Region": 6
  },
  {
    "id": "southeast_91",
    "RegionName": "Southeast",
    "SiteName": "Sixteenth Street Community Health Centers - 20th Street",
    "SiteAddress": "2906 S 20th St",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Sixteenth Street Community Health Center",
    "XCoordinate": -87.93841228,
    "YCoordinate": 42.99213648,
    "website": "https://www.wphca.org/sixteenth-st-workforce",
    "Region": 6
  },
  {
    "id": "southeast_92",
    "RegionName": "Southeast",
    "SiteName": "Sixteenth Street Community Health Centers - Chavez",
    "SiteAddress": "1032 S Cesar E Chavez Dr",
    "SiteCity": "Milwaukee",
    "HealthCenterName": "Sixteenth Street Community Health Center",
    "XCoordinate": -87.93300561,
    "YCoordinate": 43.02046585,
    "website": "https://www.wphca.org/sixteenth-st-workforce",
    "Region": 6
  }
]